# Site settings
title: Art Frick
email: artfrick@gmail.com
url: http://www.artfrick.com
description: "Art likes building things: relationships, accessible technologies, teams. He's a PMP-certified project manager working at the University of New Hampshire's Institute on Disability. He spends his time in New York City and the Hudson Valley, is almost done with his MBA, and likes eating weird things."
skills: "PMP, MBA (in May!), Accessibility Evangelist"
meta_author: Frick Art

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 110F96 #B6A898
  primary-rgb: "17,15,150" #"128,179,255"
  secondary: 111111 #B6A898
  secondary-dark: 07075b #504A43

# Footer settings
footer:
  copyright: Art Frick
  location: Location
  social: Visit Art on the Web!
  credits: How is this made? 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/artfrick  
  - title: linkedin
    url: http://www.linkedin.com/in/artfrick
  - title: instagram
    url: https://www.instagram.com/frickstock   
  - title: github
    url: http://github.com/artfrick

# Postal address (add as many lines as necessary, oy!)
address:
- line: 'Art lives in the NYC area and is reachable via social media.'

# Credits content
credits: 'This site is based off a theme by <a href="https://github.com/jeromelachaud" target="_blank">jeromelachaud</a>, powered by <a href="http://getbootstrap.com/" target="_blank">Twitter Bootstrap</a> and <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>, and hosted on <a href="http://github.com" target="_blank">Github</a>.'

# Build settings
markdown: kramdown
permalink: pretty
