# Site settings
title: Art Frick
email: artfrick@gmail.com
url: http://www.artfrick.com
description: "Art Frick is a web designer, developer, and online accessibility specialist in New York."
skills: "Designer - Developer - Online Accessibility Specialist"
meta_author: Frick Art

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: B200FD #80B3FF
  primary-rgb: "35,0,53" #"128,179,255"
  secondary: 111111 #FD6E8A
  secondary-dark: 210033 #A2122F

# Footer settings
footer:
  copyright: Art Frick
  location: Location
  social: On the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/artfrick
  - title: drupal
    url: http://www.drupal.org/u/artfrick
  - title: github
    url: http://github.com/artfrick

# Postal address (add as many lines as necessary)
address:
  - line: Mamaroneck, New York
  - line: in Westchester - The BEST chester

# Credits content
credits: 'This site is based off a theme by <a href="https://github.com/jeromelachaud" target="_blank">jeromelachaud</a>, powered by <a href="http://getbootstrap.com/" target="_blank">Twitter Bootstrap</a> and <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>, and hosted on <a href="http://github.com" target="_blank">Github</a>.'

# Build settings
markdown: kramdown
permalink: pretty
