# Site settings
title: Art Frick
email: artfrick@gmail.com
url: http://www.artfrick.com
description: "Art Frick is a web designer, developer, and online accessibility specialist in New York."
skills: "Web Developer - Online Accessibility Specialist"
meta_author: Frick Arthur

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Art Frick
  location: Where are you?
  social: On the web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:http://www.facebook.com/artfrick
  - title: github
    url: http://github.com/artfrick

# Postal address (add as many lines as necessary)
address:
  - line: Westchester, NY
  - line: The BEST-Chester

# Credits content
credits: 'This site is powered by <a href="http://getbootstrap.com/" target="_blank">Twitter Bootstrap</a> and <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>, and hosted on <a href="http://github.com" target="_blank">Github</a>'

# Build settings
markdown: kramdown
permalink: pretty
